version: "3.9"
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: master
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: laravel
        ports:
            - 3306:3306
        volumes:
            - ./data:/var/lib/mysql
