version: "3.5"

services:
  postgres:
    container_name: postgres_crud
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "${DB_PORT}:5432"
    restart: always
